pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }

        stage('Release'){
            steps{
                // This is where you'd put commands to create a release (e.g., tag the code, update version numbers)
                echo 'Creating a release...'
                sh 'git tag -a v1.0.0 -m "Release version 1.0.0"'
                sh 'git push origin v1.0.0'
            }
   
         }
    }
}
